global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 5
  width: 100 # 40.0
  height: 100 # 40.0
  resolution: 0.08 #0.05
  origin_x: -20.0
  origin_y: -20.0
  static_map: false #true
  rolling_window: true #false
